import "./globals.css";
import "@fontsource/noto-sans-lao";
import ReduxProvider from "@/components/ReduxProvider";

export const metadata = {
  title: "Mittaphab Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-noto-sans-lao">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
